INSERT INTO docs2.laboratories (description, name, url_picture, supervisor_id) VALUES ('test desc', 'Интеллектуалдық жүйелерді басқару мен болжамдау зертханасы', 'lab-7.png', 7);
INSERT INTO docs2.laboratories (description, name, url_picture, supervisor_id) VALUES (null, 'Инновациялық және смарт технологиялар зертханасы', 'lab-11.png', 11);
INSERT INTO docs2.laboratories (description, name, url_picture, supervisor_id) VALUES (null, 'Жүйелік талдау және басқару зертханасы', 'lab-1.png', 3);
INSERT INTO docs2.laboratories (description, name, url_picture, supervisor_id) VALUES (null, 'Компьютерлік криминалистика және бағдарламалық қамтамасыз ету зертханасы', 'lab-14.png', 14);
INSERT INTO docs2.laboratories (description, name, url_picture, supervisor_id) VALUES (null, 'Жасанды интеллект және робототехника зертханасы', 'lab-8.png', 8);
INSERT INTO docs2.laboratories (description, name, url_picture, supervisor_id) VALUES (null, 'Интеллектуалды жүйелер және технологиялар зертханасы', 'lab-16.png', 15);
INSERT INTO docs2.laboratories (description, name, url_picture, supervisor_id) VALUES (null, 'Аэроғарыштық технологиялар зертханасы', 'lab-13.png', 13);
INSERT INTO docs2.laboratories (description, name, url_picture, supervisor_id) VALUES (null, 'Ақпараттық үдерістерді талдау және модельдеу зертханасы', 'lab-9.png', 9);
INSERT INTO docs2.laboratories (description, name, url_picture, supervisor_id) VALUES (null, 'Интеллектуалдық жүйелердің компьютерлік инженериясы зертханасы', 'lab-12.png', 12);
INSERT INTO docs2.laboratories (description, name, url_picture, supervisor_id) VALUES (null, 'Бейнелерді тану және шешімдер қабылдау зертханасы', 'lab-2.png', 4);
INSERT INTO docs2.laboratories (description, name, url_picture, supervisor_id) VALUES (null, 'Математикалық кибернетика және есептеу технологиялары зертханасы', 'lab-5.png', 6);
INSERT INTO docs2.laboratories (description, name, url_picture, supervisor_id) VALUES (null, 'Ақпараттық қауіпсіздік зертханасы', 'lab-3.png', 5);
INSERT INTO docs2.laboratories (description, name, url_picture, supervisor_id) VALUES (null, 'Үлкен деректерді интеллектуалды талдау зертханасы', 'lab-10.png', 10);
